<a href="https://colab.research.google.com/github/DhrubaAdhikary/Learn_MMIR_with_Dhruv/blob/master/Textual_IR_components.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Information Retrieval and NLP Concepts Demonstration

This notebook provides a step-by-step demonstration of various Natural Language Processing (NLP) and Information Retrieval (IR) concepts. Due to limitations, the content of `Presentation2.pptx` could not be directly parsed, so generic examples are used to illustrate each concept.

## Setup: Installing and Importing Libraries

In [ ]:
# Install NLTK (Natural Language Toolkit) for text processing
!pip install nltk

# Import necessary libraries
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords, wordnet
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Download NLTK data (punkt for tokenization, wordnet for lemmatization, stopwords)
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')
nltk.download('omw-1.4')
nltk.download('punkt_tab') # Added to resolve LookupError

print("Setup complete: NLTK and other libraries installed and data downloaded.")

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Setup complete: NLTK and other libraries installed and data downloaded.

## 1. Document and Document Parsing

A document in NLP is a piece of text. Document parsing involves cleaning and preparing the text for further processing. This typically includes lowercasing, removing punctuation, and sometimes removing numbers or special characters.

In [ ]:
# Sample Documents
document1 = "The quick brown fox jumps over the lazy dog. The dog barks loudly."
document2 = "Foxes are clever animals. They hunt small prey. The quick fox is agile."
document3 = "A lazy dog sleeps all day. A big dog is a good companion."

corpus = [document1, document2, document3]

print("Original Document 1:", document1)
print("Original Document 2:", document2)
print("Original Document 3:", document3)

# --- Document Parsing ---
# Convert to lowercase and remove punctuation
import re

def parse_document(doc):
    # Convert to lowercase
    doc = doc.lower()
    print(f"\nAfter lowercasing: {doc}")
    # Remove punctuation
    doc = re.sub(r'[^a-z\s]', '', doc) # Keep only letters and spaces
    print(f"After removing punctuation: {doc}")
    return doc

parsed_corpus = [parse_document(doc) for doc in corpus]

print("\nParsed Corpus:")
for i, doc in enumerate(parsed_corpus):
    print(f"  Document {i+1}: {doc}")

Original Document 1: The quick brown fox jumps over the lazy dog. The dog barks loudly.
Original Document 2: Foxes are clever animals. They hunt small prey. The quick fox is agile.
Original Document 3: A lazy dog sleeps all day. A big dog is a good companion.

After lowercasing: the quick brown fox jumps over the lazy dog. the dog barks loudly.
After removing punctuation: the quick brown fox jumps over the lazy dog the dog barks loudly

After lowercasing: foxes are clever animals. they hunt small prey. the quick fox is agile.
After removing punctuation: foxes are clever animals they hunt small prey the quick fox is agile

After lowercasing: a lazy dog sleeps all day. a big dog is a good companion.
After removing punctuation: a lazy dog sleeps all day a big dog is a good companion

Parsed Corpus:
  Document 1: the quick brown fox jumps over the lazy dog the dog barks loudly
  Document 2: foxes are clever animals they hunt small prey the quick fox is agile
  Document 3: a lazy dog sleeps all day a big dog is a good companion

## 2. Tokenization

Tokenization is the process of breaking down a text into smaller units called tokens. These tokens can be words (word tokenization) or sentences (sentence tokenization).

In [ ]:
sample_text = "This is an example sentence for tokenization. It contains multiple words and punctuation marks!"

print("Original Text:", sample_text)

# --- Sentence Tokenization ---
sentences = sent_tokenize(sample_text)
print("\nSentence Tokenization:")
for i, s in enumerate(sentences):
    print(f"  Sentence {i+1}: {s}")

# --- Word Tokenization ---
# Using one of the parsed documents for word tokenization
example_doc = parsed_corpus[0]
words = word_tokenize(example_doc)

print(f"\nOriginal Parsed Document for Word Tokenization: '{example_doc}'")
print("Word Tokenization:", words)

# Tokenize all parsed documents
tokenized_corpus = [word_tokenize(doc) for doc in parsed_corpus]
print("\nTokenized Corpus (words):")
for i, tokens in enumerate(tokenized_corpus):
    print(f"  Document {i+1} tokens: {tokens}")

Original Text: This is an example sentence for tokenization. It contains multiple words and punctuation marks!

Sentence Tokenization:
  Sentence 1: This is an example sentence for tokenization.
  Sentence 2: It contains multiple words and punctuation marks!

Original Parsed Document for Word Tokenization: 'the quick brown fox jumps over the lazy dog the dog barks loudly'
Word Tokenization: ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog', 'the', 'dog', 'barks', 'loudly']

Tokenized Corpus (words):
  Document 1 tokens: ['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog', 'the', 'dog', 'barks', 'loudly']
  Document 2 tokens: ['foxes', 'are', 'clever', 'animals', 'they', 'hunt', 'small', 'prey', 'the', 'quick', 'fox', 'is', 'agile']
  Document 3 tokens: ['a', 'lazy', 'dog', 'sleeps', 'all', 'day', 'a', 'big', 'dog', 'is', 'a', 'good', 'companion']

## 3. Lemmatization

Lemmatization is the process of reducing words to their base or root form (lemma), which is a valid word in the dictionary. It uses vocabulary and morphological analysis.

In [ ]:
lemmatizer = WordNetLemmatizer()

words_to_lemmatize = ['running', 'runs', 'ran', 'better', 'best', 'dogs', 'geese']

print("Original words for Lemmatization:", words_to_lemmatize)

lemmatized_words = [lemmatizer.lemmatize(word) for word in words_to_lemmatize]
print("\nLemmatized words (default POS='n' for noun):", lemmatized_words)

# Lemmatization with Part-of-Speech (POS) tagging can improve accuracy
# For 'better'/'best', the lemma for adjective is 'good'
print("\nLemmatizing 'better' as adjective:", lemmatizer.lemmatize('better', pos='a'))
print("Lemmatizing 'best' as adjective:", lemmatizer.lemmatize('best', pos='a'))
print("Lemmatizing 'running' as verb:", lemmatizer.lemmatize('running', pos='v'))

# Apply lemmatization to our tokenized corpus
lemmatized_corpus = []
for doc_tokens in tokenized_corpus:
    lemmatized_doc = [lemmatizer.lemmatize(token) for token in doc_tokens]
    lemmatized_corpus.append(lemmatized_doc)

print("\nLemmatized Corpus:")
for i, tokens in enumerate(lemmatized_corpus):
    print(f"  Document {i+1} lemmas: {tokens}")

Original words for Lemmatization: ['running', 'runs', 'ran', 'better', 'best', 'dogs', 'geese']

Lemmatized words (default POS='n' for noun): ['running', 'run', 'ran', 'better', 'best', 'dog', 'goose']

Lemmatizing 'better' as adjective: good
Lemmatizing 'best' as adjective: best
Lemmatizing 'running' as verb: run

Lemmatized Corpus:
  Document 1 lemmas: ['the', 'quick', 'brown', 'fox', 'jump', 'over', 'the', 'lazy', 'dog', 'the', 'dog', 'bark', 'loudly']
  Document 2 lemmas: ['fox', 'are', 'clever', 'animal', 'they', 'hunt', 'small', 'prey', 'the', 'quick', 'fox', 'is', 'agile']
  Document 3 lemmas: ['a', 'lazy', 'dog', 'sleep', 'all', 'day', 'a', 'big', 'dog', 'is', 'a', 'good', 'companion']

## 4. Stemming (Porter Stemming Step by Step)

Stemming is a heuristic process that chops off the ends of words in the hope of correctly reducing words to their root form (stem). The Porter Stemmer is a common algorithm.

Here, we'll show its application and then illustrate the *idea* of step-by-step reduction, as the NLTK implementation provides the final stem directly.

In [ ]:
stemmer = PorterStemmer()

words_to_stem = ['running', 'runs', 'runner', 'ran', 'connection', 'connected', 'connective', 'universal', 'universality']

print("Original words for Stemming:", words_to_stem)

stemmed_words = [stemmer.stem(word) for word in words_to_stem]
print("\nStemmed words:", stemmed_words)

# --- Porter Stemming Step-by-Step (Illustrative) ---
print("\n--- Illustrative Porter Stemming Steps ---")

def illustrate_stemming(word, stemmer_obj):
    print(f"\nProcessing word: '{word}'")
    current_word = word
    # Note: NLTK's PorterStemmer directly applies all rules.
    # The 'steps' below are illustrative of the *types* of transformations Porter Stemmer makes,
    # not a direct output of intermediate NLTK stemmer states.

    # Example: Plural removal (Step 1a)
    if current_word.endswith('sses'):
        current_word = current_word[:-2] # e.g., 'caresses' -> 'caress'
        print(f"  Rule (SSES -> SS): {current_word}")
    elif current_word.endswith('ies'):
        current_word = current_word[:-3] + 'i' # e.g., 'flies' -> 'fli'
        print(f"  Rule (IES -> I): {current_word}")
    elif current_word.endswith('ss'): # No change for 'ss' in 1a
        print(f"  Rule (SS -> SS): {current_word}")
    elif current_word.endswith('s') and len(current_word) > 2 and current_word[-2] not in 'aeiou': # Simplified 's' removal
        current_word = current_word[:-1]
        print(f"  Rule (S -> ): {current_word}")

    # Example: Ed/Ing removal (Step 1b, 1c) - very simplified
    if current_word.endswith('eed'):
        if len(current_word) > 4: # placeholder for measure condition
            current_word = current_word[:-1]
            print(f"  Rule (EED -> EE): {current_word}")
    elif current_word.endswith('ed'):
        current_word = current_word[:-2]
        print(f"  Rule (ED -> ): {current_word}")
    elif current_word.endswith('ing'):
        current_word = current_word[:-3]
        print(f"  Rule (ING -> ): {current_word}")

    # Example: Suffix removal (Steps 2, 3, 4) - very simplified
    if current_word.endswith('tional'):
        current_word = current_word[:-2]
        print(f"  Rule (TIONAL -> TION): {current_word}")
    elif current_word.endswith('izer'):
        current_word = current_word[:-1]
        print(f"  Rule (IZER -> IZE): {current_word}")

    final_stem = stemmer_obj.stem(word)
    print(f"  Final Stem (using NLTK): {final_stem}")

illustrate_stemming('caresses', stemmer)
illustrate_stemming('ponies', stemmer)
illustrate_stemming('cats', stemmer)
illustrate_stemming('running', stemmer)
illustrate_stemming('universal', stemmer)
illustrate_stemming('privatization', stemmer) # An example where many steps apply

# Apply stemming to our tokenized corpus
stemmed_corpus = []
for doc_tokens in tokenized_corpus:
    stemmed_doc = [stemmer.stem(token) for token in doc_tokens]
    stemmed_corpus.append(stemmed_doc)

print("\nStemmed Corpus:")
for i, tokens in enumerate(stemmed_corpus):
    print(f"  Document {i+1} stems: {tokens}")

Original words for Stemming: ['running', 'runs', 'runner', 'ran', 'connection', 'connected', 'connective', 'universal', 'universality']

Stemmed words: ['run', 'run', 'runner', 'ran', 'connect', 'connect', 'connect', 'univers', 'univers']

--- Illustrative Porter Stemming Steps ---

Processing word: 'caresses'
  Rule (SSES -> SS): caress
  Final Stem (using NLTK): caress

Processing word: 'ponies'
  Rule (IES -> I): poni
  Final Stem (using NLTK): poni

Processing word: 'cats'
  Rule (S -> ): cat
  Final Stem (using NLTK): cat

Processing word: 'running'
  Rule (ING -> ): runn
  Final Stem (using NLTK): run

Processing word: 'universal'
  Final Stem (using NLTK): univers

Processing word: 'privatization'
  Final Stem (using NLTK): privat

Stemmed Corpus:
  Document 1 stems: ['the', 'quick', 'brown', 'fox', 'jump', 'over', 'the', 'lazi', 'dog', 'the', 'dog', 'bark', 'loudli']
  Document 2 stems: ['fox', 'are', 'clever', 'anim', 'they', 'hunt', 'small', 'prey', 'the', 'quick', 'fox', 'is', 'agil']
  Document 3 stems: ['a', 'lazi', 'dog', 'sleep', 'all', 'day', 'a', 'big', 'dog', 'is', 'a', 'good', 'companion']

## 5. Boolean Information Retrieval with Term-Document Matrix

Boolean retrieval models documents as a set of terms and queries as boolean expressions. A Term-Document Matrix (TDM) records the presence or absence of a term in a document.

In [ ]:
# Let's use the lemmatized corpus for better term consistency
processed_corpus_text = [" ".join(doc) for doc in lemmatized_corpus]

# Create a list of all unique terms (vocabulary)
all_terms = sorted(list(set(term for doc in lemmatized_corpus for term in doc)))

print("Vocabulary:", all_terms)
print("\nCorpus (processed):")
for i, doc_text in enumerate(processed_corpus_text):
    print(f"  Document {i+1}: {doc_text}")

# --- Construct Term-Document Matrix (TDM) ---
tdm_data = []
for doc_tokens in lemmatized_corpus:
    row = [1 if term in doc_tokens else 0 for term in all_terms]
    tdm_data.append(row)

tdm_df = pd.DataFrame(tdm_data, columns=all_terms, index=[f'Doc {i+1}' for i in range(len(corpus))])

print("\nTerm-Document Matrix (Binary):")
display(tdm_df)

# --- Boolean Queries ---
def boolean_query(query_str, tdm, all_terms_list):
    # Example: 'fox AND dog'
    # Example: 'fox OR animal'
    # Example: 'fox AND NOT lazy'

    query_tokens = query_str.lower().split()

    # Helper to get term vector
    def get_term_vector(term):
        if term in all_terms_list:
            return tdm[term]
        else:
            return pd.Series([0] * len(tdm), index=tdm.index) # Term not found

    result_vector = None
    operator = None

    i = 0
    while i < len(query_tokens):
        token = query_tokens[i]

        if token == 'not':
            # Handle NOT operator with the next term
            i += 1
            term_to_negate = query_tokens[i]
            current_term_vec = 1 - get_term_vector(term_to_negate) # Invert presence/absence
            print(f"  Processing NOT {term_to_negate}:\n{current_term_vec.to_dict()}")

            if result_vector is None:
                result_vector = current_term_vec
            elif operator == 'and':
                result_vector = result_vector & current_term_vec
            elif operator == 'or':
                result_vector = result_vector | current_term_vec
            operator = None # Reset operator after use

        elif token in ['and', 'or']:
            operator = token

        else:
            # This is a term
            current_term_vec = get_term_vector(token)
            print(f"  Processing term {token}:\n{current_term_vec.to_dict()}")

            if result_vector is None:
                result_vector = current_term_vec
            elif operator == 'and':
                result_vector = result_vector & current_term_vec
            elif operator == 'or':
                result_vector = result_vector | current_term_vec
            operator = None # Reset operator after use
        i += 1

    if result_vector is None:
        return []

    relevant_docs = result_vector[result_vector == 1].index.tolist()
    return relevant_docs

print("\n--- Executing Boolean Queries ---")

query1 = "fox AND dog"
print(f"\nQuery: '{query1}'")
result1 = boolean_query(query1, tdm_df, all_terms)
print(f"  Documents for '{query1}': {result1}")

query2 = "fox OR animal"
print(f"\nQuery: '{query2}'")
result2 = boolean_query(query2, tdm_df, all_terms)
print(f"  Documents for '{query2}': {result2}")

query3 = "dog AND NOT lazy"
print(f"\nQuery: '{query3}'")
result3 = boolean_query(query3, tdm_df, all_terms)
print(f"  Documents for '{query3}': {result3}")

query4 = "clever AND prey"
print(f"\nQuery: '{query4}'")
result4 = boolean_query(query4, tdm_df, all_terms)
print(f"  Documents for '{query4}': {result4}")

Vocabulary: ['a', 'agile', 'all', 'animal', 'are', 'bark', 'big', 'brown', 'clever', 'companion', 'day', 'dog', 'fox', 'good', 'hunt', 'is', 'jump', 'lazy', 'loudly', 'over', 'prey', 'quick', 'sleep', 'small', 'the', 'they']

Corpus (processed):
  Document 1: the quick brown fox jump over the lazy dog the dog bark loudly
  Document 2: fox are clever animal they hunt small prey the quick fox is agile
  Document 3: a lazy dog sleep all day a big dog is a good companion

Term-Document Matrix (Binary):

,a,agile,all,animal,are,bark,big,brown,clever,companion,...,jump,lazy,loudly,over,prey,quick,sleep,small,the,they
Doc 1,0,0,0,0,0,1,0,1,0,0,...,1,1,1,1,0,1,0,0,1,0
Doc 2,0,1,0,1,1,0,0,0,1,0,...,0,0,0,0,1,1,0,1,1,1
Doc 3,1,0,1,0,0,0,1,0,0,1,...,0,1,0,0,0,0,1,0,0,0

--- Executing Boolean Queries ---

Query: 'fox AND dog'
  Processing term fox:
{'Doc 1': 1, 'Doc 2': 1, 'Doc 3': 0}
  Processing term dog:
{'Doc 1': 1, 'Doc 2': 0, 'Doc 3': 1}
  Documents for 'fox AND dog': ['Doc 1']

Query: 'fox OR animal'
  Processing term fox:
{'Doc 1': 1, 'Doc 2': 1, 'Doc 3': 0}
  Processing term animal:
{'Doc 1': 0, 'Doc 2': 1, 'Doc 3': 0}
  Documents for 'fox OR animal': ['Doc 1', 'Doc 2']

Query: 'dog AND NOT lazy'
  Processing term dog:
{'Doc 1': 1, 'Doc 2': 0, 'Doc 3': 1}
  Processing NOT lazy:
{'Doc 1': 0, 'Doc 2': 1, 'Doc 3': 0}
  Documents for 'dog AND NOT lazy': []

Query: 'clever AND prey'
  Processing term clever:
{'Doc 1': 0, 'Doc 2': 1, 'Doc 3': 0}
  Processing term prey:
{'Doc 1': 0, 'Doc 2': 1, 'Doc 3': 0}
  Documents for 'clever AND prey': ['Doc 2']

## 6. Inverted Index

An inverted index is a data structure that maps words or terms to the documents in which they appear. It's fundamental for fast text search.

In [ ]:
# --- Building an Inverted Index ---
inverted_index = {}
stop_words = set(stopwords.words('english'))

for doc_id, doc_tokens in enumerate(lemmatized_corpus):
    # Remove stop words for building the index (optional but common)
    filtered_tokens = [token for token in doc_tokens if token not in stop_words]

    for term in filtered_tokens:
        if term not in inverted_index:
            inverted_index[term] = set()
        inverted_index[term].add(f'Doc {doc_id+1}')

print("Inverted Index:")
for term, doc_ids in sorted(inverted_index.items()):
    print(f"  '{term}': {sorted(list(doc_ids))}")

# --- Querying the Inverted Index ---
def query_inverted_index(query_term, inv_index):
    query_term = lemmatizer.lemmatize(query_term.lower()) # Lemmatize query term
    print(f"\nQuerying for term: '{query_term}'")
    if query_term in stop_words:
        print(f"  '{query_term}' is a stop word, might not be in index.")
        return []

    results = inv_index.get(query_term, set())
    return sorted(list(results))

print("\n--- Executing Inverted Index Queries ---")

query_term1 = "fox"
result_docs1 = query_inverted_index(query_term1, inverted_index)
print(f"  Documents containing '{query_term1}': {result_docs1}")

query_term2 = "dog"
result_docs2 = query_inverted_index(query_term2, inverted_index)
print(f"  Documents containing '{query_term2}': {result_docs2}")

query_term3 = "animal"
result_docs3 = query_inverted_index(query_term3, inverted_index)
print(f"  Documents containing '{query_term3}': {result_docs3}")

query_term4 = "car"
result_docs4 = query_inverted_index(query_term4, inverted_index)
print(f"  Documents containing '{query_term4}': {result_docs4}")

Inverted Index:
  'agile': ['Doc 2']
  'animal': ['Doc 2']
  'bark': ['Doc 1']
  'big': ['Doc 3']
  'brown': ['Doc 1']
  'clever': ['Doc 2']
  'companion': ['Doc 3']
  'day': ['Doc 3']
  'dog': ['Doc 1', 'Doc 3']
  'fox': ['Doc 1', 'Doc 2']
  'good': ['Doc 3']
  'hunt': ['Doc 2']
  'jump': ['Doc 1']
  'lazy': ['Doc 1', 'Doc 3']
  'loudly': ['Doc 1']
  'prey': ['Doc 2']
  'quick': ['Doc 1', 'Doc 2']
  'sleep': ['Doc 3']
  'small': ['Doc 2']

--- Executing Inverted Index Queries ---

Querying for term: 'fox'
  Documents containing 'fox': ['Doc 1', 'Doc 2']

Querying for term: 'dog'
  Documents containing 'dog': ['Doc 1', 'Doc 3']

Querying for term: 'animal'
  Documents containing 'animal': ['Doc 2']

Querying for term: 'car'
  Documents containing 'car': []

## 7. Query Expansion and Thesaurus Creation

Query expansion involves modifying a user's query to improve retrieval performance, often by adding synonyms or related terms. A thesaurus (or lexicon) is a collection of such related terms.

In [ ]:
# --- Simple Thesaurus Creation (Manual) ---
thesaurus = {
    'quick': ['fast', 'rapid', 'speedy'],
    'lazy': ['idle', 'slothful', 'indolent'],
    'dog': ['canine', 'hound'],
    'fox': ['vixen', 'canid']
}

print("Defined Thesaurus:", thesaurus)

# --- Query Expansion Function ---
def expand_query(original_query, thesaurus_dict, num_expansions=1):
    expanded_terms = set(original_query.lower().split())
    print(f"\nOriginal Query: '{original_query}'")
    print(f"  Initial terms: {list(expanded_terms)}")

    for _ in range(num_expansions):
        newly_added_terms = set()
        for term in list(expanded_terms): # Iterate over a copy to allow modification
            if term in thesaurus_dict:
                for synonym in thesaurus_dict[term]:
                    if synonym not in expanded_terms:
                        newly_added_terms.add(synonym)
        if not newly_added_terms:
            break # No new terms added, stop expansion
        expanded_terms.update(newly_added_terms)
        print(f"  Expanded terms after a round: {list(expanded_terms)}")

    return ' '.join(sorted(list(expanded_terms)))

print("\n--- Executing Query Expansion ---")

query_to_expand1 = "lazy dog"
expanded_query1 = expand_query(query_to_expand1, thesaurus)
print(f"Expanded Query for '{query_to_expand1}': '{expanded_query1}'")

query_to_expand2 = "quick fox"
expanded_query2 = expand_query(query_to_expand2, thesaurus)
print(f"Expanded Query for '{query_to_expand2}': '{expanded_query2}'")

query_to_expand3 = "animal"
expanded_query3 = expand_query(query_to_expand3, thesaurus)
print(f"Expanded Query for '{query_to_expand3}': '{expanded_query3}'")

Defined Thesaurus: {'quick': ['fast', 'rapid', 'speedy'], 'lazy': ['idle', 'slothful', 'indolent'], 'dog': ['canine', 'hound'], 'fox': ['vixen', 'canid']}

--- Executing Query Expansion ---

Original Query: 'lazy dog'
  Initial terms: ['lazy', 'dog']
  Expanded terms after a round: ['slothful', 'lazy', 'idle', 'canine', 'dog', 'hound', 'indolent']
Expanded Query for 'lazy dog': 'canine dog hound idle indolent lazy slothful'

Original Query: 'quick fox'
  Initial terms: ['quick', 'fox']
  Expanded terms after a round: ['fast', 'quick', 'fox', 'canid', 'speedy', 'vixen', 'rapid']
Expanded Query for 'quick fox': 'canid fast fox quick rapid speedy vixen'

Original Query: 'animal'
  Initial terms: ['animal']
Expanded Query for 'animal': 'animal'

## 8. TF-IDF based Retrieval

TF-IDF (Term Frequency-Inverse Document Frequency) is a numerical statistic that reflects how important a word is to a document in a collection or corpus. It's commonly used for weighting terms in information retrieval.

In [ ]:
# Using the processed_corpus_text from before
print("Corpus for TF-IDF:")
for i, doc_text in enumerate(processed_corpus_text):
    print(f"  Document {i+1}: {doc_text}")

# --- TF-IDF Vectorization ---
# Initialize TfidfVectorizer
# We'll include stop words here, but in real scenarios, they are often removed before TF-IDF
tfidf_vectorizer = TfidfVectorizer()

# Fit the vectorizer to the corpus and transform the corpus into TF-IDF features
tfidf_matrix = tfidf_vectorizer.fit_transform(processed_corpus_text)

# Get feature names (terms)
feature_names = tfidf_vectorizer.get_feature_names_out()

print("\nTF-IDF Matrix Shape:", tfidf_matrix.shape)
print("Vocabulary (Feature Names):", feature_names)

# Convert TF-IDF matrix to DataFrame for better readability
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=feature_names, index=[f'Doc {i+1}' for i in range(len(corpus))])
print("\nTF-IDF Matrix:")
display(tfidf_df)

# --- TF-IDF based Retrieval ---
def retrieve_documents_tfidf(query_text, vectorizer, tfidf_matrix_corpus):
    print(f"\nRetrieving documents for query: '{query_text}'")
    # Transform the query into TF-IDF vector
    query_vec = vectorizer.transform([query_text.lower()])
    print(f"  Query TF-IDF vector shape: {query_vec.shape}")

    # Calculate cosine similarity between query vector and all document vectors
    cosine_similarities = cosine_similarity(query_vec, tfidf_matrix_corpus).flatten()

    # Create a DataFrame to display scores
    results_df = pd.DataFrame({
        'Document': [f'Doc {i+1}' for i in range(len(corpus))],
        'Similarity Score': cosine_similarities
    })

    # Sort by similarity score in descending order
    ranked_results = results_df.sort_values(by='Similarity Score', ascending=False)

    print("  Cosine Similarities with Documents:", cosine_similarities)
    print("\n  Ranked Retrieval Results:")
    display(ranked_results)

    return ranked_results

print("\n--- Executing TF-IDF Retrieval ---")

query_tfidf1 = "quick brown dog"
retrieve_documents_tfidf(query_tfidf1, tfidf_vectorizer, tfidf_matrix)

query_tfidf2 = "clever animal"
retrieve_documents_tfidf(query_tfidf2, tfidf_vectorizer, tfidf_matrix)

Corpus for TF-IDF:
  Document 1: the quick brown fox jump over the lazy dog the dog bark loudly
  Document 2: fox are clever animal they hunt small prey the quick fox is agile
  Document 3: a lazy dog sleep all day a big dog is a good companion

TF-IDF Matrix Shape: (3, 25)
Vocabulary (Feature Names): ['agile' 'all' 'animal' 'are' 'bark' 'big' 'brown' 'clever' 'companion'
 'day' 'dog' 'fox' 'good' 'hunt' 'is' 'jump' 'lazy' 'loudly' 'over' 'prey'
 'quick' 'sleep' 'small' 'the' 'they']

TF-IDF Matrix:

,agile,all,animal,are,bark,big,brown,clever,companion,day,...,jump,lazy,loudly,over,prey,quick,sleep,small,the,they
Doc 1,0.00000,0.00000,0.00000,0.00000,0.264866,0.00000,0.264866,0.00000,0.00000,0.00000,...,0.264866,0.201437,0.264866,0.264866,0.00000,0.201437,0.00000,0.00000,0.604311,0.00000
Doc 2,0.28809,0.00000,0.28809,0.28809,0.000000,0.00000,0.000000,0.28809,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.28809,0.219100,0.00000,0.28809,0.219100,0.28809
Doc 3,0.00000,0.32495,0.00000,0.00000,0.000000,0.32495,0.000000,0.00000,0.32495,0.32495,...,0.000000,0.247132,0.000000,0.000000,0.00000,0.000000,0.32495,0.00000,0.000000,0.00000

--- Executing TF-IDF Retrieval ---

Retrieving documents for query: 'quick brown dog'
  Query TF-IDF vector shape: (1, 25)
  Cosine Similarities with Documents: [0.49329835 0.1134622  0.25595815]

  Ranked Retrieval Results:

  Document  Similarity Score
0    Doc 1          0.493298
2    Doc 3          0.255958
1    Doc 2          0.113462

Retrieving documents for query: 'clever animal'
  Query TF-IDF vector shape: (1, 25)
  Cosine Similarities with Documents: [0.         0.40742077 0.        ]

  Ranked Retrieval Results:

  Document  Similarity Score
1    Doc 2          0.407421
0    Doc 1          0.000000
2    Doc 3          0.000000

  Document  Similarity Score
1    Doc 2          0.407421
0    Doc 1          0.000000
2    Doc 3          0.000000

## 9. Vector Space Model, Query & Document Representation, and Cosine Similarity

In the Vector Space Model (VSM), documents and queries are represented as vectors in a multi-dimensional space, where each dimension corresponds to a term in the vocabulary. The similarity between a query and a document is often calculated using cosine similarity.

In [ ]:
# We've already calculated TF-IDF vectors, which are a common way to represent documents in VSM.
# The `tfidf_matrix` contains our document vectors.

print("--- Document Vectors (TF-IDF based) ---")
# Displaying the TF-IDF matrix again as it represents our document vectors
print("Document Vectors:")
display(tfidf_df)

# --- Query Vector Representation ---
query_vsm = "quick fox"
print(f"\nQuery: '{query_vsm}'")

# Transform the query into a TF-IDF vector using the *same* vectorizer fitted on the corpus
query_vector = tfidf_vectorizer.transform([query_vsm.lower()])
query_vector_dense = query_vector.toarray().flatten()

print("  Query Vector (TF-IDF):")
query_vector_df = pd.DataFrame([query_vector_dense], columns=feature_names)
display(query_vector_df)

# --- Cosine Similarity Calculation ---
# We already did this in the TF-IDF retrieval section, but let's re-emphasize the calculation.

print("\n--- Cosine Similarity Calculation (Query vs. Documents) ---")

# Reshape query_vector_dense for cosine_similarity if needed (sklearn handles it for sparse matrices)
# Or convert tfidf_matrix to dense for manual calculation

doc_vectors_dense = tfidf_matrix.toarray()

cosine_scores = []
for i, doc_vector in enumerate(doc_vectors_dense):
    # np.dot(A, B) / (np.linalg.norm(A) * np.linalg.norm(B))
    # Ensure non-zero norms to avoid division by zero for empty vectors
    if np.linalg.norm(query_vector_dense) > 0 and np.linalg.norm(doc_vector) > 0:
        score = np.dot(query_vector_dense, doc_vector) / (np.linalg.norm(query_vector_dense) * np.linalg.norm(doc_vector))
    else:
        score = 0.0 # If either vector is all zeros, similarity is 0
    cosine_scores.append(score)
    print(f"  Cosine Similarity (Query, Doc {i+1}): {score:.4f}")

results_vsm_df = pd.DataFrame({
    'Document': [f'Doc {i+1}' for i in range(len(corpus))],
    'Cosine Similarity': cosine_scores
}).sort_values(by='Cosine Similarity', ascending=False)

print("\nRanked Documents by Cosine Similarity:")
display(results_vsm_df)

--- Document Vectors (TF-IDF based) ---
Document Vectors:

,agile,all,animal,are,bark,big,brown,clever,companion,day,...,jump,lazy,loudly,over,prey,quick,sleep,small,the,they
Doc 1,0.00000,0.00000,0.00000,0.00000,0.264866,0.00000,0.264866,0.00000,0.00000,0.00000,...,0.264866,0.201437,0.264866,0.264866,0.00000,0.201437,0.00000,0.00000,0.604311,0.00000
Doc 2,0.28809,0.00000,0.28809,0.28809,0.000000,0.00000,0.000000,0.28809,0.00000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.28809,0.219100,0.00000,0.28809,0.219100,0.28809
Doc 3,0.00000,0.32495,0.00000,0.00000,0.000000,0.32495,0.000000,0.00000,0.32495,0.32495,...,0.000000,0.247132,0.000000,0.000000,0.00000,0.000000,0.32495,0.00000,0.000000,0.00000

Query: 'quick fox'
  Query Vector (TF-IDF):

,agile,all,animal,are,bark,big,brown,clever,companion,day,...,jump,lazy,loudly,over,prey,quick,sleep,small,the,they
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.707107,0.0,0.0,0.0,0.0

--- Cosine Similarity Calculation (Query vs. Documents) ---
  Cosine Similarity (Query, Doc 1): 0.2849
  Cosine Similarity (Query, Doc 2): 0.4648
  Cosine Similarity (Query, Doc 3): 0.0000

Ranked Documents by Cosine Similarity:

  Document  Cosine Similarity
1    Doc 2           0.464781
0    Doc 1           0.284875
2    Doc 3           0.000000

## 10. Evaluation Methods: Precision, Recall, F1 Score, and Ranked Evaluations

Evaluating information retrieval systems involves measuring how well they retrieve relevant documents and rank them. Common metrics include Precision, Recall, F1-score, and for ranked lists, Average Precision (AP) and Mean Average Precision (MAP).

In [ ]:
# --- Scenario Setup for Evaluation ---
# Let's assume a hypothetical query 'animals' and define ground truth relevant documents.

# Our documents:
# Doc 1: The quick brown fox jumps over the lazy dog. The dog barks loudly.
# Doc 2: Foxes are clever animals. They hunt small prey. The quick fox is agile.
# Doc 3: A lazy dog sleeps all day. A big dog is a good companion.

# Ground Truth: Assume for the query 'animals', Doc 2 and Doc 3 are relevant.
# (Doc 1 mentions 'fox' and 'dog', but Doc 2 explicitly uses 'animals' and Doc 3 is about 'dog')

ground_truth_relevant_docs = {'Doc 2', 'Doc 3'}

print("Ground Truth Relevant Documents:", ground_truth_relevant_docs)

# --- Hypothetical Retrieval Results ---
# Case 1: An unranked list of retrieved documents
retrieved_docs_unranked = ['Doc 2', 'Doc 1'] # The system retrieved Doc 2 and Doc 1
print("\nHypothetical Unranked Retrieval Results:", retrieved_docs_unranked)

# --- Precision, Recall, F1 Score (for unranked retrieval) ---
def calculate_pr_f1(retrieved, ground_truth):
    true_positives = len(ground_truth.intersection(set(retrieved)))
    false_positives = len(set(retrieved) - ground_truth)
    false_negatives = len(ground_truth - set(retrieved))

    print(f"  True Positives (retrieved & relevant): {true_positives}")
    print(f"  False Positives (retrieved & not relevant): {false_positives}")
    print(f"  False Negatives (not retrieved & relevant): {false_negatives}")

    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0
    f1_score = (2 * precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

    print(f"  Precision: {precision:.4f}")
    print(f"  Recall: {recall:.4f}")
    print(f"  F1 Score: {f1_score:.4f}")
    return precision, recall, f1_score

print("\n--- Evaluation for Unranked Retrieval ---")
calculate_pr_f1(retrieved_docs_unranked, ground_truth_relevant_docs)

# Case 2: A ranked list of retrieved documents for Average Precision (AP)
# Let's say our system returned documents in this order for the 'animals' query:
# Doc 2 (Relevant), Doc 1 (Not Relevant), Doc 3 (Relevant)
ranked_retrieval_results = [
    ('Doc 2', True), # True means relevant
    ('Doc 1', False),
    ('Doc 3', True),
    ('Doc 4', False) # Hypothetical, not in our original corpus, but good for demo
]

print("\nHypothetical Ranked Retrieval Results (with relevance judgment):")
for doc, is_relevant in ranked_retrieval_results:
    print(f"  {doc}: {'Relevant' if is_relevant else 'Not Relevant'}")

# --- Average Precision (AP) for a single query ---
def calculate_average_precision(ranked_results, ground_truth_set):
    num_relevant_docs = len(ground_truth_set)
    if num_relevant_docs == 0: return 0.0

    sum_precision = 0.0
    num_retrieved_relevant = 0

    print("\n  Calculating Average Precision:")
    for i, (doc_id, is_relevant) in enumerate(ranked_results):
        rank = i + 1
        print(f"    At rank {rank}, document {doc_id} is {'relevant' if is_relevant else 'not relevant'}")
        if is_relevant:
            num_retrieved_relevant += 1
            precision_at_rank = num_retrieved_relevant / rank
            sum_precision += precision_at_rank
            print(f"      -> Relevant found. Precision@{rank} = {precision_at_rank:.4f}, Current Sum Precision = {sum_precision:.4f}")
        else:
            print(f"      -> Not relevant.")

    ap = sum_precision / num_relevant_docs if num_relevant_docs > 0 else 0.0
    print(f"  Total relevant docs in ground truth: {num_relevant_docs}")
    print(f"  Average Precision (AP): {ap:.4f}")
    return ap

print("\n--- Evaluation for Ranked Retrieval (Average Precision) ---")
ap_score = calculate_average_precision(ranked_retrieval_results, ground_truth_relevant_docs)

# --- Mean Average Precision (MAP) for multiple queries ---
# MAP is the mean of the Average Precision scores for a set of queries.
# Let's simulate another query.

# Query 2: 'lazy dog'
# Ground Truth: {'Doc 1', 'Doc 3'}
# Ranked Results for Q2:
ranked_retrieval_results_q2 = [
    ('Doc 3', True),
    ('Doc 1', True),
    ('Doc 2', False)
]
ground_truth_relevant_docs_q2 = {'Doc 1', 'Doc 3'}

print("\n--- Evaluation for Ranked Retrieval (Mean Average Precision - MAP) ---")

print("\nQuery 1 ('animals'):")
ap1 = calculate_average_precision(ranked_retrieval_results, ground_truth_relevant_docs)

print("\nQuery 2 ('lazy dog'):")
ap2 = calculate_average_precision(ranked_retrieval_results_q2, ground_truth_relevant_docs_q2)

map_score = (ap1 + ap2) / 2
print(f"\nMean Average Precision (MAP) for 2 queries: ({ap1:.4f} + {ap2:.4f}) / 2 = {map_score:.4f}")

Ground Truth Relevant Documents: {'Doc 3', 'Doc 2'}

Hypothetical Unranked Retrieval Results: ['Doc 2', 'Doc 1']

--- Evaluation for Unranked Retrieval ---
  True Positives (retrieved & relevant): 1
  False Positives (retrieved & not relevant): 1
  False Negatives (not retrieved & relevant): 1
  Precision: 0.5000
  Recall: 0.5000
  F1 Score: 0.5000

Hypothetical Ranked Retrieval Results (with relevance judgment):
  Doc 2: Relevant
  Doc 1: Not Relevant
  Doc 3: Relevant
  Doc 4: Not Relevant

--- Evaluation for Ranked Retrieval (Average Precision) ---

  Calculating Average Precision:
    At rank 1, document Doc 2 is relevant
      -> Relevant found. Precision@1 = 1.0000, Current Sum Precision = 1.0000
    At rank 2, document Doc 1 is not relevant
      -> Not relevant.
    At rank 3, document Doc 3 is relevant
      -> Relevant found. Precision@3 = 0.6667, Current Sum Precision = 1.6667
    At rank 4, document Doc 4 is not relevant
      -> Not relevant.
  Total relevant docs in ground truth: 2
  Average Precision (AP): 0.8333

--- Evaluation for Ranked Retrieval (Mean Average Precision - MAP) ---

Query 1 ('animals'):

  Calculating Average Precision:
    At rank 1, document Doc 2 is relevant
      -> Relevant found. Precision@1 = 1.0000, Current Sum Precision = 1.0000
    At rank 2, document Doc 1 is not relevant
      -> Not relevant.
    At rank 3, document Doc 3 is relevant
      -> Relevant found. Precision@3 = 0.6667, Current Sum Precision = 1.6667
    At rank 4, document Doc 4 is not relevant
      -> Not relevant.
  Total relevant docs in ground truth: 2
  Average Precision (AP): 0.8333

Query 2 ('lazy dog'):

  Calculating Average Precision:
    At rank 1, document Doc 3 is relevant
      -> Relevant found. Precision@1 = 1.0000, Current Sum Precision = 1.0000
    At rank 2, document Doc 1 is relevant
      -> Relevant found. Precision@2 = 1.0000, Current Sum Precision = 2.0000
    At rank 3, document Doc 2 is not relevant
      -> Not relevant.
  Total relevant docs in ground truth: 2
  Average Precision (AP): 1.0000

Mean Average Precision (MAP) for 2 queries: (0.8333 + 1.0000) / 2 = 0.9167

## Conclusion

This notebook has covered key concepts in Document Processing, Natural Language Processing (Tokenization, Lemmatization, Stemming), and Information Retrieval (Boolean Model, Inverted Index, TF-IDF, Vector Space Model, Query Expansion, and Evaluation Metrics). Each step demonstrated the application and intermediate results for better understanding.